### ISSUE TITLE
System of "proposition of events

### ISSUE THREAD

**Issue by WaKeMaTTa** [PazMundial/website#2]
**TODO**

- [ ] Unconfirmed user sees information about asking to confirm his account, to be able to do more things.
- [ ] Confirmed user can propose an event.
- [ ] Confirmed user can propose an event.

Events proposition.
