### ISSUE TITLE
System of "proposition of events"

### ISSUE THREAD

**Issue by WaKeMaTTa** [PazMundial/website#3]
**TODO**

- [ ] Unconfirmed user sees information about asking to confirm his account, to be able to do more things.
- [ ] Confirmed user can propose an event.
- [ ] Administrator can accept or reject propositons.
  - [ ] When is accepted or rejected an email is sent to the author of the event.
- [ ] An author of the event can discard an event.
  - [ ] If this event was in status accepted, an email is sent to the administrators.

**More infomation**

*An event* has:

- [ ] (required) Title
- [ ] (required) Descriptión
- [ ] (required) Link of youtube channel
- [ ] (required) DateTime start in UTC
- [ ] (required) DateTime ends in UTC
- [ ] (optional) Participation is public?
- [ ] (optional) Categories

*Caracteristics of an event*:

- The time of an event cannot overlap with another event.

**Gems**

- `sendgrid-ruby` https://rubygems.org/gems/sendgrid-ruby
- `aasm` https://rubygems.org/gems/aasm
